/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as MilitaryRouteImport } from './routes/military'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CorpersRouteImport } from './routes/corpers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const MilitaryRoute = MilitaryRouteImport.update({
  id: '/military',
  path: '/military',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpersRoute = CorpersRouteImport.update({
  id: '/corpers',
  path: '/corpers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/corpers': typeof CorpersRoute
  '/departments': typeof DepartmentsRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/military': typeof MilitaryRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/corpers': typeof CorpersRoute
  '/departments': typeof DepartmentsRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/military': typeof MilitaryRoute
  '/staff': typeof StaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/announcements': typeof AnnouncementsRoute
  '/contact': typeof ContactRoute
  '/corpers': typeof CorpersRoute
  '/departments': typeof DepartmentsRoute
  '/documents': typeof DocumentsRoute
  '/gallery': typeof GalleryRoute
  '/kitchen': typeof KitchenRoute
  '/military': typeof MilitaryRoute
  '/staff': typeof StaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/corpers'
    | '/departments'
    | '/documents'
    | '/gallery'
    | '/kitchen'
    | '/military'
    | '/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/corpers'
    | '/departments'
    | '/documents'
    | '/gallery'
    | '/kitchen'
    | '/military'
    | '/staff'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/announcements'
    | '/contact'
    | '/corpers'
    | '/departments'
    | '/documents'
    | '/gallery'
    | '/kitchen'
    | '/military'
    | '/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ContactRoute: typeof ContactRoute
  CorpersRoute: typeof CorpersRoute
  DepartmentsRoute: typeof DepartmentsRoute
  DocumentsRoute: typeof DocumentsRoute
  GalleryRoute: typeof GalleryRoute
  KitchenRoute: typeof KitchenRoute
  MilitaryRoute: typeof MilitaryRoute
  StaffRoute: typeof StaffRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/military': {
      id: '/military'
      path: '/military'
      fullPath: '/military'
      preLoaderRoute: typeof MilitaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpers': {
      id: '/corpers'
      path: '/corpers'
      fullPath: '/corpers'
      preLoaderRoute: typeof CorpersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ContactRoute: ContactRoute,
  CorpersRoute: CorpersRoute,
  DepartmentsRoute: DepartmentsRoute,
  DocumentsRoute: DocumentsRoute,
  GalleryRoute: GalleryRoute,
  KitchenRoute: KitchenRoute,
  MilitaryRoute: MilitaryRoute,
  StaffRoute: StaffRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
